services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - web:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    restart: unless-stopped
  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    environment:
      - DB_HOST=${DB_HOST}
      - DB_AUSR=${DB_AUSR}
      - DB_APW=${DB_APW}
      - DB_NAME=${DB_NAME}
      - WP_URL=${WP_URL}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_EMAIL=${WP_EMAIL}
      - WP_PASSWORD=${WP_PASSWORD}
    volumes:
      - web:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    restart: unless-stopped
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    environment:
      - DB_RPW=${DB_RPW}
      - DB_NAME=${DB_NAME}
      - DB_AUSR=${DB_AUSR}
      - DB_APW=${DB_APW}
      - DB_USR=${DB_USR}
      - DB_PW=${DB_PW}
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped
volumes:
  web:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mmonika/data/wordpress
  database:
    driver: local  
    driver_opts:
      type: none
      o: bind
      device: /home/mmonika/data/mdb
networks:
  inception:
    driver: bridge
