version: '3'
services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
  wordpress:
    build: requirements/wordpress
    container_name: wordpress
  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      -"443:443"
networks:
